// Export comparison analysis as Markdown or prepare for PDF generation

export interface AnalysisData {
  summary: string;
  keyChanges: string[];
  designChanges: string[];
  contentChanges: string[];
  businessInsights: string[];
}

export interface ExportData {
  url: string;
  earlierDate: string;
  laterDate: string;
  analysis: AnalysisData;
  generatedAt: string;
}

// Generate Markdown report
export function generateMarkdownReport(data: ExportData): string {
  const { url, earlierDate, laterDate, analysis, generatedAt } = data;
  
  return `# TimeBack Analysis Report

**Website:** ${url}
**Comparison Period:** ${earlierDate} → ${laterDate}
**Generated:** ${generatedAt}

---

## Summary

${analysis.summary}

---

## Key Changes

${analysis.keyChanges.map((change, i) => `${i + 1}. ${change}`).join('\n')}

---

## Design Evolution

${analysis.designChanges.map(change => `- ${change}`).join('\n')}

---

## Content Shifts

${analysis.contentChanges.map(change => `- ${change}`).join('\n')}

---

## Business Insights

${analysis.businessInsights.map(insight => `> ${insight}`).join('\n\n')}

---

## Archived Snapshots

- **Earlier:** [View on Wayback Machine](https://web.archive.org/web/${earlierDate.replace(/-/g, '')}/${url})
- **Later:** [View on Wayback Machine](https://web.archive.org/web/${laterDate.replace(/-/g, '')}/${url})

---

*Report generated by [TimeBack](https://timeback.vercel.app) - Visual Website Time Machine*
`;
}

// Generate HTML report (for PDF conversion)
export function generateHTMLReport(data: ExportData): string {
  const { url, earlierDate, laterDate, analysis, generatedAt } = data;
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TimeBack Analysis - ${url}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    h1 { font-size: 28px; margin-bottom: 8px; color: #0a0a0a; }
    h2 { font-size: 20px; margin: 32px 0 16px; color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
    .meta { color: #6b7280; font-size: 14px; margin-bottom: 32px; }
    .meta span { display: block; margin: 4px 0; }
    .summary { 
      background: #f3f4f6; 
      padding: 20px; 
      border-radius: 8px; 
      margin: 20px 0;
      border-left: 4px solid #2563eb;
    }
    ul, ol { margin: 12px 0; padding-left: 24px; }
    li { margin: 8px 0; }
    blockquote { 
      background: #fffbeb; 
      border-left: 4px solid #f59e0b; 
      padding: 16px; 
      margin: 12px 0;
      border-radius: 0 8px 8px 0;
    }
    .section { margin: 24px 0; }
    .footer { 
      margin-top: 48px; 
      padding-top: 24px; 
      border-top: 1px solid #e5e7eb; 
      font-size: 12px; 
      color: #9ca3af;
      text-align: center;
    }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .badge {
      display: inline-block;
      background: #2563eb;
      color: white;
      font-size: 12px;
      padding: 4px 8px;
      border-radius: 4px;
      margin-right: 8px;
    }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <h1>🕐 TimeBack Analysis Report</h1>
  <div class="meta">
    <span><strong>Website:</strong> ${url}</span>
    <span><strong>Comparison:</strong> ${earlierDate} → ${laterDate}</span>
    <span><strong>Generated:</strong> ${generatedAt}</span>
  </div>

  <h2>📋 Summary</h2>
  <div class="summary">
    ${analysis.summary}
  </div>

  <h2>🔑 Key Changes</h2>
  <div class="section">
    <ol>
      ${analysis.keyChanges.map(change => `<li>${change}</li>`).join('\n      ')}
    </ol>
  </div>

  <h2>🎨 Design Evolution</h2>
  <div class="section">
    <ul>
      ${analysis.designChanges.map(change => `<li>${change}</li>`).join('\n      ')}
    </ul>
  </div>

  <h2>📝 Content Shifts</h2>
  <div class="section">
    <ul>
      ${analysis.contentChanges.map(change => `<li>${change}</li>`).join('\n      ')}
    </ul>
  </div>

  <h2>💡 Business Insights</h2>
  <div class="section">
    ${analysis.businessInsights.map(insight => `<blockquote>${insight}</blockquote>`).join('\n    ')}
  </div>

  <h2>🔗 View Archives</h2>
  <div class="section">
    <p>
      <a href="https://web.archive.org/web/${earlierDate.replace(/-/g, '')}/${url}" target="_blank">
        <span class="badge">Earlier</span> View ${earlierDate} on Wayback Machine
      </a>
    </p>
    <p style="margin-top: 8px;">
      <a href="https://web.archive.org/web/${laterDate.replace(/-/g, '')}/${url}" target="_blank">
        <span class="badge">Later</span> View ${laterDate} on Wayback Machine
      </a>
    </p>
  </div>

  <div class="footer">
    Report generated by <a href="https://timeback.vercel.app">TimeBack</a> - Visual Website Time Machine
  </div>
</body>
</html>`;
}

// Download helper - creates a downloadable file
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Download as Markdown
export function downloadMarkdown(data: ExportData): void {
  const markdown = generateMarkdownReport(data);
  const filename = `timeback-${data.url.replace(/[^a-zA-Z0-9]/g, '-')}-${data.laterDate}.md`;
  downloadFile(markdown, filename, 'text/markdown');
}

// Download as HTML (can be printed to PDF from browser)
export function downloadHTML(data: ExportData): void {
  const html = generateHTMLReport(data);
  const filename = `timeback-${data.url.replace(/[^a-zA-Z0-9]/g, '-')}-${data.laterDate}.html`;
  downloadFile(html, filename, 'text/html');
}

// Open HTML in new tab for printing
export function openForPrint(data: ExportData): void {
  const html = generateHTMLReport(data);
  const newWindow = window.open();
  if (newWindow) {
    newWindow.document.write(html);
    newWindow.document.close();
    // Wait for content to load then trigger print
    setTimeout(() => {
      newWindow.print();
    }, 500);
  }
}
